repos:
  - repo: local
    hooks:
      - id: isort
        name: Run isort on staged Python files
        entry: isort
        language: system
        types: [python]
        args: [--skip, pyproject.toml, --gitignore]
      - id: black
        name: Run black on staged Python files
        entry: black
        language: system
        types: [python]
        args: [-l, "79"]
      - id: ruff
        name: Run ruff on staged Python files
        entry: ruff check --fix
        language: system
        types: [python]
      - id: make-clean
        name: Run make clean
        entry: make clean
        language: system
        files: ''
        pass_filenames: false
        always_run: true 
      - id: make-docs-lint
        name: Run make docs-lint
        entry: make docs-lint
        language: system
        files: ^docs/.*\.(rst|md)$
        pass_filenames: false
      - id: rstfmt
        name: Run rstfmt on staged documentation files
        entry: rstfmt -w 120
        language: system
        files: ^docs/.*\.rst$
      - id: make-docs-clean
        name: Run make docs clean
        entry: make docs-clean
        language: system
        files: ''
        pass_filenames: false
        always_run: true 

